# Generated by Django 5.0.6 on 2024-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_facility_order_trip_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='facilities',
            field=models.ManyToManyField(related_name='busses', to='station.facility'),
        ),
    ]
